name: flutter_media_picker
description: A new Flutter package for accessing local storage medias .
version: 0.0.1
homepage: https://github.com/novaday-co/flutter_media_picker/

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  bottom_sheet: ^4.0.4
  photo_manager: ^3.2.3
  camera: ^0.11.0+2
  image_cropper: ^6.0.0
  flutter:
    sdk: flutter
  dropdown_button2: ^3.0.0-beta.19
  skeleton_text: ^3.0.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  gallery_saver_plus: ^3.1.1
#  gallery_saver: ^2.3.2
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  camera_android:
    git:
      url: https://github.com/elmar001/plugins.git
      path: packages/camera/camera_android
      ref: 5172b44088a4082ff0899594614c5380457d341b

flutter:

