name: flutter_media_picker
description: A new Flutter package for accessing local storage medias .
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  photo_manager: ^2.1.4
  dropdown_button2: ^1.7.2
  flutter:
    sdk: flutter
  bottom_sheet: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

